version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: postgresdb
    environment:
      - POSTGRES_DB=memberDb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist database data
    networks:
      - myNetwork

volumes:
  postgres-data:
    driver: local

networks:
  myNetwork:
    driver: bridge